### ISSUE TITLE
Site doesn't load on older browsers

### ISSUE THREAD

**Issue by jasonkarns** [homebridge/homebridge.io#1]
Running macOS Mountain Lion. Which is the _absolute latest_ macOS that is supported on 2007 mac mini.
Running Firefox 45. Which is the latest secure release of Firefox that supports Mountain Lion.

This is homebridge.io homepage:

![Screen Shot 2020-08-13 at 12 54 39 PM](https://user-images.githubusercontent.com/119972/90164002-d815d900-dd64-11ea-994a-77bf092872a8.png)

This is extremely frustrating for a variety of reasons. The first being that older hardware is _particularly_ useful for running homebridge servers. This isn't an edge case as it might be for many other websites; but is likely a very significant chunk of users.

But secondly (and even more frustrating), the content of the homebridge.io website does not necessitate the use of JavaScript. 99% of the site is static content. There is no reason that it should require JS for initial render at all; least of all _modern_ JS.

**Comment by oznu** [comment]
Fixed with https://github.com/homebridge/homebridge.io/commit/95ddcc1a0b0501ce3215b8c95577d16e84ca6716

**Comment by jasonkarns** [comment]
🚀 loads great now, thanks!!!
